DOUBLE total_cut_peaks      (PARAMS *g, AREA *A, COMMAND *cmd, int begin, int end);
DOUBLE total_rectify_save   (PARAMS *g, AREA *A, COMMAND *cmd, int begin, int end);
DOUBLE total_sub_mean       (PARAMS *g, AREA *A, COMMAND *cmd, int begin, int end);
DOUBLE total_sub_mean_col   (PARAMS *g, AREA *A, COMMAND *cmd, int begin, int end);
DOUBLE total_average        (PARAMS *g, AREA *A, COMMAND *cmd, int begin, int end);
DOUBLE total_sub_min        (PARAMS *g, AREA *A, COMMAND *cmd, int begin, int end);
DOUBLE total_set_mean       (PARAMS *g, AREA *A, COMMAND *cmd, int begin, int end);
DOUBLE total_time_mean      (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE all_time_mean        (PARAMS *g, AREA *A, COMMAND *cmd, int begin, int end);
DOUBLE total_set_attime     (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_epoche_mean    (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_epoche_x_square(PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_epoche_x_fourth(PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_epoche_kurt    (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_import         (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_back_pipe      (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_copy_back      (PARAMS *g, AREA *A, COMMAND *cmd, int begin, int end);
DOUBLE total_embed          (PARAMS *g, AREA *A, COMMAND *cmd, int begin, int end);
DOUBLE total_embed_tiles    (PARAMS *g, AREA *A, COMMAND *cmd, int begin, int end);
DOUBLE total_spread_time    (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_spread_xy      (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_set_all        (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_collapse_xy    (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_mean_to_one    (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_spherize       (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_normalize      (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_scale_to_max   (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_threshold      (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_true_softmax   (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_true_softmax_row (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_four           (PARAMS *g, AREA *A, COMMAND *cmd, int begin, int end);
DOUBLE total_mult_compl     (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_absq_compl     (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_geom_vector_sum(PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_zhang_m_fix    (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_orange         (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_cosinus        (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_gabor          (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_gauss_elliptic (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_cos            (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_cut_at         (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_shift_torus    (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_winner         (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_winner_per_row (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_neigh_winner   (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_neigh_winner_3D(PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_fit_gauss      (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_gauss_at       (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_softmax        (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_error_at       (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE gnuplot_error_at     (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_dist_xy_middle (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_rand           (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_as_rand        (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_any_nonzero    (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_pause          (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);

DOUBLE total_behaviour      (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_real_world     (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_init_behaviour (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_high_vision    (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_mult_const_if  (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_set_nth        (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_swap_nth       (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_copy_nth       (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_rand_nth       (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_compare_with   (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_compare_count  (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);

DOUBLE total_retina_to_SC   (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_population_motor_row (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_population_motor_2D  (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_scalar_mult    (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_change_active_by     (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_converge_to    (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
DOUBLE total_mean_left_min_right (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);

DOUBLE total_topo_gibbs_01  (PARAMS *g, AREA *A, COMMAND *cmd, int ct_t, int dummy);
